export const requests = [
  {
    id: 1,
    urgency: "urgent",
    tag: "Urgent · Expires 25m",
    distance: "0.4 km away",
    title: "Assorted Fresh Produce",
    detail: "Quantity: 15kg · Whole Foods Market",
    lat: 40.4210,
    lng: -3.7038,
  },
  {
    id: 2,
    urgency: "standard",
    tag: "Standard · Expires 3h",
    distance: "1.2 km away",
    title: "Artisanal Breads & Bagels",
    detail: "Quantity: 40 units · Hearthstone Bakery",
    lat: 40.4245,
    lng: -3.6940,
  },
  {
    id: 3,
    urgency: "standard",
    tag: "Standard · Expires 5h",
    distance: "2.8 km away",
    title: "Dairy Pack (Milk/Yogurt)",
    detail: "Quantity: 12 packs · Green Valley Dairy",
    lat: 40.4055,
    lng: -3.7180,
  },
  {
    id: 4,
    urgency: "standard",
    tag: "Standard · Expires 6h",
    distance: "3.5 km away",
    title: "Packaged Sandwiches",
    detail: "Quantity: 25 items · Metro Deli",
    lat: 40.4330,
    lng: -3.6870,
  },
];